
server:    
  port: 5100

spring:   
  application:
    name: mybatis-generator
  
  datasource:
    url: jdbc:mysql://localhost:3306/acc-prinum?autoReconnect=true&allowMultiQueries=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
